# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03b71b2d276893c090de3032de818d4c86c7c9182b3f218bd09d5e911d2d2d3ffd1e861a988e2bf0f64392ad06a50527b66a6dde3fe4f09c2b6ad9470e91c8b3

test:
  secret_key_base: 866db7c4b832c859dcb83c467dadddea1e8009655fce1e3ced7021640055417f0c830aa5f4b1a935eed2a9ed6788cca625bb564c78004fc5fc6acff354568baf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
